version: "3.9"
services:
  django:
    container_name: django-app
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - ".env"
    depends_on:
      - postgres
    volumes:
      - ./log/django/:/log/django/
    networks:
      - django-network
  postgres:
    container_name: postgres-serv
    image: postgres:14-alpine
    restart: always
    env_file:
      - ".env"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - django-network

volumes:
  postgres-data:

networks:
  django-network:
    driver: bridge