version: "3.9"
services:
  django:
    container_name: django-app
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - django-network
  postgres:
    container_name: postgres-serv
    image: postgres:14-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - django-network
  nginx:
    build: ./nginx/
    container_name: nginx-serv
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs/:/var/log/nginx
      - ./nginx/cache/:/etc/nginx/cache
    ports:
      - "80:80"
    networks:
      - django-network
    depends_on:
      - django
    restart: always

volumes:
  postgres-data:

networks:
  django-network:
    driver: bridge